### ISSUE TITLE
FR - Auto-pick correct language

### ISSUE THREAD

**Issue by johans3** [joethei/obsidian-tts#11]
Instead to use a rigid code like this:
`lang: {languageCode}`
Use **word frequently**
https://lexiteria.com/word_frequency_list.html

... to identify the right target language. 
Asian languages are even easier to detect, in my experience. 😄

**Comment by joethei** [comment]
This has been implemented in 0.5.0.

As automatic detection is never perfect you might still need to use the frontmatter method sometimes.

**Comment by johans3** [comment]
> As automatic detection is never perfect you might still need to use the frontmatter method sometimes.

Indeed, i myself cut comparisons down to only 30 words per language, better you choose more sample words but i let this detail up to you. 
Results aren't perfect, but results are nice 🙂

Glad, you did implement this feature
