### ISSUE TITLE
only 2 shortcuts instead of 4

### ISSUE THREAD

**Issue by 1C0D** [joethei/obsidian-tts#23]
pause and resume playback shortcuts are not needed. 
doing Start playblack it should start. and then doing the same shortcut again it should pause. and again resume. and then another shortcut to stop. (like the pluging Read Aloud in firefox chrome).  Much simpler and free shortcuts are precious...

**Comment by qazero** [comment]
Any update on this?

**Comment by jurassicparkin** [comment]
I would also like this feature please!
(Just found this plugin and it's awesome, thanks!)

**Comment by 1C0D** [comment]
@jurassicparkin  done should be ok

**Comment by jurassicparkin** [comment]
Ah awesome thanks, much appreciated! 😊

**Comment by 1C0D** [comment]
@jurassicparkin  oh  thought I edited my message. I did an update, and it has to be accepted (pullrequest)

**Comment by 1C0D** [comment]
@jurassicparkin 
I did a release so you can use it. Uninstall the plugin. Just put the manifest.json file and main.js in a folder with same name as plugin in your vault's plugins folder and don't install the plugin over it.
https://github.com/1C0D/obsidian-tts-modif/releases/tag/0.5.1.beta

**Comment by jurassicparkin** [comment]
Hi, thanks for your message. I did as you instructed and restarted Obsidian but now it doesn't show up in Settings (in Community Plugins or Hotkeys) and I can't run it from the Command Palette. Is there another step I'm missing?
Thanks

**Comment by jurassicparkin** [comment]
Awesome, it's working 😄 Thanks for your help!

**Comment by 1C0D** [comment]
I hope the author of this repo is not ignoring me because I did several tries before to do it well.

**Comment by joethei** [comment]
I am not ignoring you, I just have a busy job.

Anyway, update released, thank you for your contribution.
