### ISSUE TITLE
Which TTS Service are you using? [I want to contribute to add a speech speed function but cant find documentation]

### ISSUE THREAD

**Issue by ianTevesAcc** [joethei/obsidian-tts#33]
I wanna contribute and add a speed manipulation, but I cant find the tts service your using and its docs.
Could you direct me or give me any insight that will help in understanding of your plug ins architecture?

**Comment by joethei** [comment]
The plugin is using the SpeechSynthesis part of the Web Speech API that's available in browsers.
<https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#speech_synthesis>

There is already a speed setting, I am not sure if it's possible to modify the speed on the fly.

**Comment by ianTevesAcc** [comment]
Thanks man! I'm a productivity freak, so I want a speed setting.
