### ISSUE TITLE
Dead in the Water

### ISSUE THREAD

**Issue by dvansoye** [joethei/obsidian-tts#34]
Sorry. But with the latest update, I can't use the plugin. I'm dyslexic and rely on this plugin. 

When I select some text to read, I get the error message. Could not use configured language. Please check your settings. Using default voice. (See screenshot.)

But, nothing is read. And, the old version was working fine.

I'm using 0.5.3.

I uninstalled and reinstalled and got the same behavior.

If there a way to fall back to the old version. Help!

See screenshot below. This is taken inside the settings.

![Screenshot 2024-02-19 094727](https://github.com/joethei/obsidian-tts/assets/14299260/e7ffb6a4-570b-4278-a5c2-a53573b5b911)

**Comment by joethei** [comment]
This should be fixed with 0.5.4.

Sorry for breaking it.
