### ISSUE TITLE
Use rendered content as text source

### ISSUE THREAD

**Issue by joethei** [joethei/obsidian-tts#4]
Currently the plugin is using the source.

This would allow for the following plugins output to be read:
- Admonitions
- Dataview
- ...

**Comment by brainoverflow98** [comment]
I have created a pull request which adds the possibility to select the text to be read from the rendered content.

**Comment by joethei** [comment]
Your PR only allows for starting the playback when in reading mode, but does allow for plugin output to be read.(Which is what this FR is for)

**Comment by brainoverflow98** [comment]
What do you mean by "plugin output" ?

**Comment by joethei** [comment]
Some plugins, like [Admonition](https://github.com/valentine195/obsidian-admonition) and [Dialogue](https://github.com/holubj/obsidian-dialogue-plugin) for example, allow for rendering
custom content by putting some code in a code block.

It would be nice to be able to listen to this output, without the surrounding code block.
This would need to happen on a plugin by plugin basis.

**Comment by brainoverflow98** [comment]
Ok will check them later.
