### ISSUE TITLE
Android mobile support

### ISSUE THREAD

**Issue by santiyounger** [joethei/obsidian-tts#8]
Hey, this plugin is amazing thank you so much for making this, I've been waiting for something like this, and it's great!

I'd love to know if it's possible to support the Obsidian mobile app, particularly in Android for my case.

I installed the plugin in Android I don't get the usual warning "this plugin is not supported in your device" installion works correctly, then when trying to use the command palette to read some text, it doesn't work

It's hard to tell if this is an issue from my side, or if it's not currently possible to use this plugin in mobile

Either way this feature would be amazing, thanks again for all your great work

**Comment by joethei** [comment]
Sadly Android is the only operating system that does not have tts exposed to Obsidian. 
see the link in the Readme.

you could install the plugin, because it does work on ios and I can only specify if the plugin works on mobile as a whole.

**Comment by santiyounger** [comment]
Got you, I understand. That's a shame but I totally get it if it's outside of your control. Still an awesome plugin that works great on PC. Keep it up
